/* eslint-disable import/prefer-default-export */

export enum EContextActionTypes {
  SET_LOADING = 'SET_LOADING',
  REGISTER_USER = 'REGISTER_USER',
  ADD_DISH = 'ADD_DISH',
  GET_USERS = 'GET_USERS',
  REMOVE_USER = 'REMOVE_USER',
  USER_ERROR = 'USER_ERROR',
  UPDATE_DISH = 'UPDATE_DISH',
  SET_CURRENT = 'SET_CURRENT',
  CLEAR_CURRENT = 'CLEAR_CURRENT',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_FAIL = 'LOGIN_FAIL',
  GET_DISHES = 'GET_DISHES',
  DISH_ERROR = 'DISH_ERROR',
  LOAD_USER = 'LOAD_USER',
  DELETE_DISH = 'DELETE_DISH',
  LOGIN = 'LOGIN',
  REGISTER_FAIL = 'REGISTER_FAIL',
  REMOVE_ALERT = 'REMOVE_ALERT',
  SET_ALERT = 'SET_ALERT',
  CLEAR_FILTER = 'CLEAR_FILTER',
  CLEAR_DISHES = 'CLEAR_DISHES',
  FILTER_CONTACTS = 'FILTER_CONTACTS',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS'
}

export interface EContextBaseAction {
  type: EContextActionTypes;
}
