import { DefaultActionsTypes } from '../types';


const contextActions: DefaultActionsTypes = {
  dishes: {
    GET_DISHES: 'GET_DISHES',
    ADD_DISH: 'ADD_DISH',
    DELETE_DISH: 'DELETE_DISH',
    SET_CURRENT: 'SET_CURRENT',
    UPDATE_DISH: 'UPDATE_DISH',
    SEARCH_DISHES: 'SEARCH_DISHES',
    CLEAR_FILTER: 'CLEAR_FILTER',
  },
  auth: {
    SET_LOADING: 'SET_LOADING',
    REGISTER_USER: 'REGISTER_USER',
    GET_USERS: 'GET_USERS',
    REMOVE_USER: 'REMOVE_USER',
    USER_ERROR: 'USER_ERROR',
    SET_CURRENT: 'SET_CURRENT',
    CLEAR_CURRENT: 'CLEAR_CURRENT',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOAD_USER: 'LOAD_USER',
    LOGIN: 'LOGIN',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REMOVE_ALERT: 'REMOVE_ALERT',
    SET_ALERT: 'SET_ALERT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOG_OUT: 'LOG_OUT',
  },
};


export default contextActions;
